default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: actioncable_cli_<%= Rails.env %>

test:
  adapter: test

<%= Rails.env %>:
  <<: *default
